---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Here are some plots

you can make plots in the same way as always

```{r message = FALSE}
library(tidyverse)

df = tibble(
  x = rnorm(100, 2, 5), 
  y = 1 +2*x - .5 * x ^ 2 + rnorm(100)
)

df |> 
ggplot(aes(x =x, y = y)) +
  geom_point()
```

today we're making interactive plots in plotly. We'll make exmples using the NYC airbnb dataset.

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Do some initial data cleaning/ subsetting.

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  drop_na(rating) |>
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)

```

Use plotly to make some plots.
```{r}
nyc_airbnb |> 
  mutate(text_label = str_c("Price: ", price, "\nNeighborhood: ", neighbourhood)) |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Nextup boxplot

```{r}
nyc_airbnb |>
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
  plot_ly(
    x = ~neighbourhood, y= ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )

```
bar chart with number of rentals

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, type = "bar", colors = "viridis")
```

```{r}
plot_ly(
  z = volcano
)
```

